pr:
  - main

jobs:
  - job: Lint
    steps:
      - checkout: self
        fetchDepth: 0

    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: 8.x
        performMultiLevelLookup: true
        includePreviewVersions: true 

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'select'
        vstsFeed: 'my-vsts-feed'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'format'