services:
  database:
    image: postgres:16
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "33647553"
      POSTGRES_DB: recipes 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - recipe

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "database"
    image: recipes-docker
    container_name: recipes 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=recipes;Username=postgres;Password=33647553
    ports:
      - '8080:8080'
    networks:
      - recipe

  pgadmin:
    depends_on:
      - "database"
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - recipe


volumes:
  postgres_data:
  pgadmin_data:

networks:
  recipe:
    driver: bridge